/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/speaking.glb");
  const { ref, actions, names } = useAnimations(animations)
  
  useEffect(() => {
    // Reset and fade in animation after an index has been changed
    
      actions[names[0]].reset().play()
    // In the clean-up phase, fade it out
    //return () => actions[names[0]].fadeOut(0.5)
  }, [ actions, names])



  return (
    <group ref={ref} {...props} dispose={null}>
      <group name="Scene">
        <group name="banorte_v6" scale={1} />
        <group
          name="Armature"
          position={props.loadingBanorte ? [0,5.8,0] : [0, -0.14, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.25}
        >
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh
            name="Body1001"
            geometry={nodes.Body1001.geometry}
            material={materials["Material.001"]}
            skeleton={nodes.Body1001.skeleton}
          />
          <skinnedMesh
            name="Body10001"
            geometry={nodes.Body10001.geometry}
            material={materials["Material.003"]}
            skeleton={nodes.Body10001.skeleton}
          />
          <skinnedMesh
            name="Body11001"
            geometry={nodes.Body11001.geometry}
            material={materials["Material.003"]}
            skeleton={nodes.Body11001.skeleton}
          />
          <skinnedMesh
            name="Body14001"
            geometry={nodes.Body14001.geometry}
            material={materials["Material.003"]}
            skeleton={nodes.Body14001.skeleton}
          />
          <skinnedMesh
            name="Body15001"
            geometry={nodes.Body15001.geometry}
            material={materials["Material.003"]}
            skeleton={nodes.Body15001.skeleton}
          />
          <skinnedMesh
            name="Body18001"
            geometry={nodes.Body18001.geometry}
            material={materials["Material.003"]}
            skeleton={nodes.Body18001.skeleton}
          />
          <skinnedMesh
            name="Body19001"
            geometry={nodes.Body19001.geometry}
            material={materials["Material.003"]}
            skeleton={nodes.Body19001.skeleton}
          />
          <skinnedMesh
            name="Body2001"
            geometry={nodes.Body2001.geometry}
            material={materials["Material.001"]}
            skeleton={nodes.Body2001.skeleton}
          />
          <skinnedMesh
            name="Body20001"
            geometry={nodes.Body20001.geometry}
            material={materials["Material.003"]}
            skeleton={nodes.Body20001.skeleton}
          />
          <skinnedMesh
            name="Body21001"
            geometry={nodes.Body21001.geometry}
            material={materials["Material.003"]}
            skeleton={nodes.Body21001.skeleton}
          />
          <skinnedMesh
            name="Body22001"
            geometry={nodes.Body22001.geometry}
            material={materials["Material.003"]}
            skeleton={nodes.Body22001.skeleton}
          />
          <skinnedMesh
            name="Body23001"
            geometry={nodes.Body23001.geometry}
            material={materials["Material.003"]}
            skeleton={nodes.Body23001.skeleton}
          />
          <skinnedMesh
            name="Body3001"
            geometry={nodes.Body3001.geometry}
            material={materials["Material.001"]}
            skeleton={nodes.Body3001.skeleton}
          />
          <skinnedMesh
            name="Body6001"
            geometry={nodes.Body6001.geometry}
            material={materials["Material.003"]}
            skeleton={nodes.Body6001.skeleton}
          />
          <skinnedMesh
            name="Body7001"
            geometry={nodes.Body7001.geometry}
            material={materials["Material.003"]}
            skeleton={nodes.Body7001.skeleton}
          />
          <skinnedMesh
            name="Body8001"
            geometry={nodes.Body8001.geometry}
            material={materials["Material.002"]}
            skeleton={nodes.Body8001.skeleton}
          />
          <skinnedMesh
            name="Body9001"
            geometry={nodes.Body9001.geometry}
            material={materials["Material.002"]}
            skeleton={nodes.Body9001.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/speaking.glb");